name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
     - name: echo a string
       run: echo "First github action"
     - name: multiline script
       run: |
         node -v
         npm -v
         jq --version
     - name: python commands
       run: |
         import platform
         print (platform.processor())
       shell: python
     - name: list files
       run: |
         pwd
         ls
     - name: checkout
       uses: actions/checkout@v1
     - name: list files after checkout 
       run: |
         pwd
         ls -a